### ISSUE TITLE
write file like image

### ISSUE THREAD

**Issue by Moonrise1275** [michael/github#172]
Can i write image (like uploaded via <input type="file">)to my github repo with github.js?
If i can, how can i do this? Just pass File object instead of string?
If i can't, is there a plan to support it?

**Comment by Moonrise1275** [comment]
Anyway, thanks for your hard work.
Cheers.

**Comment by aharris88** [comment]
I'm assuming this is possible since prose supports image uploads. But I would also like to see documentation on how to do this.

**Comment by AurelioDeRosa** [comment]
Is there any update on this request?

**Comment by AurelioDeRosa** [comment]
This is already possible using the library. Tomorrow I'll to publish an article that explains how to do that and post a link here to help everyone.

**Comment by AurelioDeRosa** [comment]
This is already possible using the library. I explain how to do that in [this article](http://www.audero.it/blog/2015/10/17/upload-files-on-github-using-github-js/). I think this issue can be closed, but I'll wait for a confirmation from other maintainers.

**Comment by aendrew** [comment]
The workaround given by @AurelioDeRosa isn't possible any more due to the unicode handling added in #203. It's really hard juggling dependencies between NodeJS-land and Browserville, so this stuff keeps breaking. I've thus added a "encode" property to the repo.write options array that, when set to `false`, assumes content will be base64-encoded elsewhere (e.g., in a FileReader or some such).

@AurelioDeRosa's article is really good and is still a good reference if trying to send images to GitHub, but please also see this spec, lines [27-42][1] and [362][2].

Closing as resolved. The "encode" property will be removed or depreciated next release as by then we'll have found a catch-all solution for handling base64 string.

[1]: https://github.com/michael/github/blob/master/test/test.repo.js#L27
[2]: https://github.com/michael/github/blob/master/test/test.repo.js#L362

**Comment by auiechko** [comment]
I have a problem, it says that `repo.write(''BRANCH_NAME'',"FILE.txt","CONTENT","YOUR_COMMIT_MESSAGE")` is not a function, can anybody help me with that problem?
