### ISSUE TITLE
What is the difference between user.userRepos and user.repos?

### ISSUE THREAD

**Issue by aendrew** [michael/github#257]
The former is awful for performance; it seems like they're roughly the same thing.

**Comment by AurelioDeRosa** [comment]
`userRepos()` and `repos()` are very similar. The only difference is that `repos()` retrieves the repositories of the authenticated user while `userRepos()` retrieves the repositories of the username provided. The reason for the difference in performance is that `userRepos()` was doing the right thing while `repos()` wasn't. To be precise, `userRepos()` was retrieving **all** the repositories of the test user that we employ for our tests. `repos()` was only retrieving the first page (e.g. the first 100 repositories).

The issue with `repos()` has been fixed in commit adcfbdda4a640b7234b6e196d46023404528f106.

In addition to that,  `userRepos()` has the problem that it didn't allow a user to specify the same options that we support in `repos()`. This has been fixed in commit 2373a36cc26e6cfe7fd9e8e2cdc00894cb8d3ac2.

**Comment by aendrew** [comment]
@AurelioDeRosa :tada: Awesome, thanks for clarifying that!
